# run me with ````docker-compose run -d crits-web . ````
#
db:
  image: percona/percona-server-mongodb:latest
  container_name: mongodb
  volumes:
  - /data/db
  expose:
  - "27017"
crits-web:
  build: crits-web_dockerfile
  container_name: crits-web
  command: python /data/crits/manage.py runserver 0.0.0.0:8080
  volumes:
  - /data/crits
  ports:
  - "8080:8080"
  links:
  - db
nginx-uwsgi:
  build: nginx-uwsgi_dockerfile
  container_name: nginx
  ports:
  - "80:80"
  links:
  - crits-web