# run me with ````docker-compose run crits-web  ````
#   #  - "443:443"
crits-web:
  build: .
  container_name: crits-web
  volumes:
  - ./certs:/data/certs
  - ./logs:/data/crits/crits.log
  ports:
  - "8080:8080"
  links:
  - db
db:
  image: percona/percona-server-mongodb:latest
  container_name: mongodb
  volumes:
  - /data/db
  expose:
  - "27017"