# run me with ````docker-compose run crits-web  ````
#
crits-web:
  build: .
  container_name: crits-web
  volumes:
  - ./certs:/data/certs
  ports:
  - "443:443"
  links:
  - db
db:
  image: percona/percona-server-mongodb:latest
  container_name: mongodb
  volumes:
  - /data/db
  expose:
  - "27017"